sudo: required 
services:
  - docker
cache:
  directories:
    - node_modules
before_install:
  - docker build -t lagaj/docker-react -f Dockerfile.dev .
script: 
  - docker run lagaj/docker-react npm test -- --watchAll=false