sudo: required 
services:
  - docker
cache:
  directories:
    - node_modules
before_install:
  - docker build -t lagaj/docker-react -f Dockerfile.dev .
script: 
  - docker run lagaj/docker-react npm run test -- --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-061076186936"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY